server:
  port: 9090  #端口
spring:
  application:
    name: ssm-demo  #项目名称
  datasource:
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #连接池类型
    druid:
      initial-size: 2  #初始化连接数
      max-active: 5 #最大连接数
      max-wait: 5000 #最大等待时间
  mvc:
    throw-exception-if-no-handler-found: true #找不到处理器，就抛出异常
  web:
    resources:
      add-mappings: false  #禁用404错误页面资源映射
mybatis:
  mapper-locations: classpath:/mappers/*.xml  #指定映射文件的位置
logging:
  level:
    com.edu: debug  #日志级别

#jwt
jwt:
  token:
    expire: 7*24*60*60*1000  #一周
    sign: asfdiahdiua12435&%$#@@  #签名

